language: swift
os: osx
osx_image: xcode10

branches:
  only:
    - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=SwiftPullToRefresh.xcodeproj
  - SCHEME="SwiftPullToRefresh"

script:
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Debug
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Release

after_success:
  - sleep 5
